---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "deployment-horizontalpodautoscaler"
spec:
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "deployment-horizontalpodautoscaler"
...
