---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  # Remote resource: GitHub
  - "github.com/automation64/kustomize-k8s-deployment-hello-world//src"
  # Remote resource: HTTPS
  - "https://raw.githubusercontent.com/istio/istio/refs/heads/master/samples/bookinfo/platform/kube/bookinfo.yaml"
...
