# Reference: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"

resources:
  - "deployment-basic.yaml"
  - "deployment-storage-emptydir.yaml"

  - "deployment-hpa.yaml"
  - "horizontalpodautoscaler.yaml"
...
