---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "service-clusterip"
  name: "service-clusterip"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "service-clusterip"
  strategy: {}
  template:
    metadata:
      labels:
        app: "service-clusterip"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 6464
      containers:
        - image: "hashicorp/http-echo"
          name: "http-echo"
          resources:
            requests:
              cpu: "10m"
              memory: "24Mi"
            limits:
              cpu: "20m"
              memory: "32Mi"
          securityContext:
            readOnlyRootFilesystem: true
          args:
            - "-text=hello-world"
            - "-listen=:8080"
            - "-status-code=200"
          ports:
            - containerPort: 8080
              name: "http"
...
