---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "service-loadbalancer"
spec:
  type: "LoadBalancer"
  selector:
    app: "service-loadbalancer"
  ports:
    - name: "http"
      port: 8080
...
