---
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "pod-basic"
  labels:
    app: "pod-basic"
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 6464
  containers:
    - image: "busybox:latest"
      name: "busybox"
      resources:
        requests:
          cpu: "10m"
          memory: "24Mi"
        limits:
          cpu: "20m"
          memory: "32Mi"
      securityContext:
        readOnlyRootFilesystem: true
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do echo 'hello world'; sleep 10; done"
...
